  application: strat-roulette
  version: 1
  runtime: python27
  api_version: 1
  threadsafe: yes

  handlers:

  - url: /favicon.ico
    secure: optional
    static_files: public/img/favicon.ico
    upload: public/img/favicon.ico

  - url: /static/(.+)
    secure: optional
    static_files: public/\1
    upload: public/(.*)

  - url: /
    secure: optional
    static_files: index.html
    upload: index.html

  - url: /(.+)
    secure: optional
    static_files: index.html
    upload: index.html

  skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^fabfile\.py
  - ^testrunner\.py
  - ^grunt\.js
  - ^node_modules/(.*/)?
